  File "/Users/valenetjong/opt/anaconda3/envs/qiskit_env/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/Users/valenetjong/opt/anaconda3/envs/qiskit_env/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
Exception: The wandb backend process has shutdown
Traceback (most recent call last):
  File "/Users/valenetjong/qiskit/hybridQNN/main.py", line 157, in <module>
    main()
  File "/Users/valenetjong/qiskit/hybridQNN/main.py", line 145, in main
    data = Data(batch_size)
  File "/Users/valenetjong/qiskit/hybridQNN/datasetmaker.py", line 9, in __init__
    self.trainloader = self.trainingdata()
  File "/Users/valenetjong/qiskit/hybridQNN/datasetmaker.py", line 24, in trainingdata
    X_train.targets = X_train.data[idx]
IndexError: index 519 is out of bounds for dimension 0 with size 200