2022-03-10 10:20:47,228 INFO    MainThread:8416 [wandb_setup.py:_flush():75] Loading settings from /Users/valenetjong/.config/wandb/settings
2022-03-10 10:20:47,229 INFO    MainThread:8416 [wandb_setup.py:_flush():75] Loading settings from /Users/valenetjong/qiskit/wandb/settings
2022-03-10 10:20:47,229 INFO    MainThread:8416 [wandb_setup.py:_flush():75] Loading settings from environment variables: {'_require_service': 'True'}
2022-03-10 10:20:47,229 INFO    MainThread:8416 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'binaryHybridQNN/main.py', 'program': '/Users/valenetjong/qiskit/binaryHybridQNN/main.py'}
2022-03-10 10:20:47,229 INFO    MainThread:8416 [wandb_init.py:_log_setup():405] Logging user logs to /Users/valenetjong/qiskit/wandb/run-20220310_102047-20g06gur/logs/debug.log
2022-03-10 10:20:47,229 INFO    MainThread:8416 [wandb_init.py:_log_setup():406] Logging internal logs to /Users/valenetjong/qiskit/wandb/run-20220310_102047-20g06gur/logs/debug-internal.log
2022-03-10 10:20:47,229 INFO    MainThread:8416 [wandb_init.py:init():439] calling init triggers
2022-03-10 10:20:47,230 INFO    MainThread:8416 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {'epochs': 20, 'batch_size': 1, 'learn_rate': 0.001, 'optimizer': 'adam', 'momentum': 0.9, 'dropout': 0.2}
2022-03-10 10:20:47,230 INFO    MainThread:8416 [wandb_init.py:init():492] starting backend
2022-03-10 10:20:47,235 INFO    MainThread:8416 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2022-03-10 10:20:47,240 INFO    MainThread:8416 [wandb_init.py:init():501] backend started and connected
2022-03-10 10:20:47,245 INFO    MainThread:8416 [wandb_init.py:init():565] updated telemetry
2022-03-10 10:20:47,247 INFO    MainThread:8416 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-03-10 10:20:47,479 INFO    MainThread:8416 [wandb_run.py:_on_init():1759] communicating current version
2022-03-10 10:20:47,640 INFO    MainThread:8416 [wandb_run.py:_on_init():1763] got version response 
2022-03-10 10:20:47,640 INFO    MainThread:8416 [wandb_init.py:init():625] starting run threads in backend
2022-03-10 10:20:47,761 WARNING MsgRouterThr:8416 [router.py:message_loop():76] message_loop has been closed
2022-03-10 10:20:52,671 INFO    MainThread:8416 [wandb_run.py:_console_start():1733] atexit reg
2022-03-10 10:20:52,671 INFO    MainThread:8416 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.WRAP
2022-03-10 10:20:52,672 INFO    MainThread:8416 [wandb_run.py:_redirect():1643] Wrapping output streams.
2022-03-10 10:20:52,673 INFO    MainThread:8416 [wandb_run.py:_redirect():1667] Redirects installed.
2022-03-10 10:20:52,689 ERROR   MainThread:8416 [wandb_init.py:init():981] error
Traceback (most recent call last):
  File "/Users/valenetjong/opt/anaconda3/envs/qiskit_env/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 954, in init
    run = wi.init()
  File "/Users/valenetjong/opt/anaconda3/envs/qiskit_env/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 662, in init
    run._on_start()
  File "/Users/valenetjong/opt/anaconda3/envs/qiskit_env/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1778, in _on_start
    self._on_ready()
  File "/Users/valenetjong/opt/anaconda3/envs/qiskit_env/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1791, in _on_ready
    self._telemetry_flush()
  File "/Users/valenetjong/opt/anaconda3/envs/qiskit_env/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 481, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/Users/valenetjong/opt/anaconda3/envs/qiskit_env/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 73, in _publish_telemetry
    self._publish(rec)
  File "/Users/valenetjong/opt/anaconda3/envs/qiskit_env/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/valenetjong/opt/anaconda3/envs/qiskit_env/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 99, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/valenetjong/opt/anaconda3/envs/qiskit_env/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 57, in send_server_request
    self._send_message(msg)
  File "/Users/valenetjong/opt/anaconda3/envs/qiskit_env/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 54, in _send_message
    self._sock.send(header + data)
BrokenPipeError: [Errno 32] Broken pipe
